image: node:20.9-alpine
stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

deploy:
  stage: deploy
  tags:
    - node
  only:
    - master
  before_script:
    - npm install
    - sudo chown -R root:$(whoami) /usr/local/lib/node_modules/
    - sudo chmod -R 775 /usr/local/lib/node_modules/
    - npm install -g vercel
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN